version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
    #api keys purposefully comitted
      METHOD_API_KEY: sk_Tf4aPU8KiBxWX8Vae8Wjwf7M
      DATABASE_URL: postgres://postgres:password@db:5432/dd?connect_timeout=300
      ENV: dev
      PORT: 5000
    command: sh -c "npx prisma migrate dev && npm start"
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
